# Generated by Django 5.0.6 on 2024-05-23 18:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('place_id', models.CharField(max_length=200, unique=True)),
                ('description_short', models.TextField()),
                ('description_long', models.TextField()),
                ('lng', models.FloatField(max_length=200)),
                ('lat', models.FloatField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('position', models.ImageField(upload_to='')),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='places.place', verbose_name='фотографии')),
            ],
        ),
    ]
